import cyberpi, mbuild

cyberpi.emotion.look_up()
cyberpi.emotion.look_down()
cyberpi.emotion.look_left()
cyberpi.emotion.look_right()
cyberpi.emotion.look_around()
cyberpi.emotion.blink()
cyberpi.emotion.smile()
cyberpi.emotion.yeah()
cyberpi.emotion.naughty()
cyberpi.emotion.proud()
cyberpi.emotion.yummy()
cyberpi.emotion.uh_oh()
cyberpi.emotion.wow()
cyberpi.emotion.hurt()
cyberpi.emotion.sad()
cyberpi.emotion.angry()
cyberpi.emotion.hello()
cyberpi.emotion.sprint()
cyberpi.emotion.startle()
cyberpi.emotion.shiver()
cyberpi.emotion.dizzy()
cyberpi.emotion.sleepy()
cyberpi.emotion.zzz()
cyberpi.emotion.wake_up()
cyberpi.emotion.yes()
cyberpi.emotion.no()
