# generated by mBlock5 for CyberPi
# codes make you happy
import time, event, cyberpi

@event.start
def on_start():
    cyberpi.display.set_brush(255, 255, 255)
    cyberpi.led.set_bri(30)
    cyberpi.audio.set_vol(50)
    cyberpi.audio.set_tempo(100)

    if cyberpi.get_language() == 'chinese':
        cyberpi.console.println('神奇录音机')
        cyberpi.console.println(' ')
        cyberpi.console.println('按下“摇杆中')
        cyberpi.console.println('间” 开始录音')
        cyberpi.led.show('orange orange orange orange orange')
    else:
        cyberpi.console.set_font(12)
        cyberpi.console.println('Magic recorder')
        cyberpi.console.println(' ')
        cyberpi.console.println('Press "joystick" to start ')
        cyberpi.led.show('orange orange orange orange orange')

@event.is_press('a')
def on_received():
    cyberpi.console.clear()

    if cyberpi.get_language() == 'chinese':
        cyberpi.console.println('按下 B 播放录音')
        cyberpi.console.println('')
        cyberpi.led.show('red red red red red')
        cyberpi.audio.stop_record()
    else:
        cyberpi.console.println('Press B to play the recording')
        cyberpi.console.println(' ')
        cyberpi.led.show('red red red red red')
        cyberpi.audio.stop_record()

@event.is_press('middle')
def is_press():
    cyberpi.console.clear()

    if cyberpi.get_language() == 'chinese':
        cyberpi.console.println('正在录音…')
        cyberpi.console.println('按下 A 停止录音')
    else:
        cyberpi.console.println('Recording……')
        cyberpi.console.println(' ')
        cyberpi.console.println('Press A to stop')
        cyberpi.console.println('')

    cyberpi.led.show('green green green green green')
    cyberpi.audio.record()

@event.is_press('b')
def on_received1():
    cyberpi.console.clear()

    if cyberpi.get_language() == 'chinese':
        cyberpi.console.println('录音播放…')
        cyberpi.console.println(' ')
        cyberpi.console.println('按下“摇杆中')
        cyberpi.console.println('间” 重新录音')
        cyberpi.led.show('blue blue blue blue blue')
        cyberpi.audio.play_record_until()
    else:
        cyberpi.console.println('Playing…')
        cyberpi.console.println(' ')
        cyberpi.console.println('Press "joystick" to start ')
        cyberpi.led.show('blue blue blue blue blue')
        cyberpi.audio.play_record_until()
