# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, random

# initialize variables
i = 0
j = 0
k = 0
m = 0
pen = cyberpi.sprite()

@event.start
def on_start():
    global i, j, k, m, pen

    cyberpi.background.fill(0, 0, 0)

    # Draw title
    pen.move_to(64, 64)
    pen.set_brush(5, 166, 255)

    if cyberpi.get_language() == 'chinese':
        pen.draw_text(' 万花尺')
    else:
        pen.draw_text('Kaleidoscopes')

    time.sleep(1)

    cyberpi.sketch.set_size(1)

    move_to_origin()
    draw_triangle()
    time.sleep(1)

    move_to_origin()
    draw_square()
    time.sleep(1)

    move_to_origin()
    draw_pentagon()


def move_to_origin():
    """Reset drawing to the center with default angle and speed"""
    cyberpi.sketch.clear()
    cyberpi.sketch.start()
    cyberpi.sketch.move_to(64, 64)
    cyberpi.sketch.set_angle(90)
    cyberpi.sketch.set_speed(10)


def change_color():
    """Set a random RGB color for sketching"""
    global i, j, k
    i = random.randint(20, 255)
    j = random.randint(20, 255)
    k = random.randint(20, 255)
    cyberpi.sketch.set_color(i, j, k)


def draw_triangle():
    """Draw triangle patterns repeatedly with rotation"""
    for _ in range(10):
        change_color()
        for _ in range(3):
            cyberpi.sketch.move(50)
            cyberpi.sketch.cw(120)
        cyberpi.sketch.cw(36)


def draw_pentagon():
    """Draw pentagon patterns repeatedly with rotation"""
    for _ in range(20):
        change_color()
        for _ in range(6):
            cyberpi.sketch.move(30)
            cyberpi.sketch.cw(60)
        cyberpi.sketch.cw(18)


def draw_square():
    """Draw square patterns repeatedly with rotation"""
    for _ in range(15):
        change_color()
        for _ in range(4):
            cyberpi.sketch.move(40)
            cyberpi.sketch.cw(90)
        cyberpi.sketch.cw(24)
